apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
  namespace: app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo
          image: theeb2000/product-services:v33
          ports:
            - containerPort: 8080
