apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-service-ingress
  namespace: ingress-nginx # <-- chỉ định namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: product.local  # <-- bạn có thể đổi tên theo ý, hoặc bỏ nếu dùng qua IP
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
