apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | b64enc | quote }}
